[package]
name = "lunar-arithmetic"
version = "0.1.1"
authors = ["sts10 <sschlinkert@gmail.com>"]
edition = "2021"
license = "BlueOak-1.0.0"

[dependencies]
eyeoh = { git = "https://github.com/sts10/eyeoh" }
